#include <iostream>
#include <string>

using namespace std;

/*
=========================================================
LeetCode 38 : Count and Say
=========================================================

The sequence is defined as:

1
11
21
1211
111221
...

Each term is generated by describing the previous term.

Example:
"21" → "one 2, one 1" → "1211"

Steps:
1. Take the previous string
2. Count consecutive characters
3. Append count + character

=========================================================
Approach 1 : Recursion + Manual Character Tracking
Approach 2 : Recursion + While Loop Counting

Time Complexity : Exponential (sequence length grows)
Space Complexity : Recursive stack
=========================================================
*/


/*
=========================================================
Approach 1
Recursion + Character Tracking
=========================================================
*/

class Solution1
{
public:

    string countAndSay(int n)
    {
        // Base case
        if (n == 1)
        {
            return "1";
        }

        // Get previous term
        string say = countAndSay(n - 1);

        string result = "";

        // Track current character and count
        char currentChar = say[0];
        int count = 1;

        // Traverse previous string
        for (int i = 1; i < say.size(); i++)
        {
            if (say[i] == currentChar)
            {
                count++;
            }
            else
            {
                // Append count and character
                result += to_string(count);
                result += currentChar;

                // Update character and reset count
                currentChar = say[i];
                count = 1;
            }
        }

        // Add last group
        result += to_string(count);
        result += currentChar;

        return result;
    }
};



/*
=========================================================
Approach 2
Recursion + While Loop Counting
=========================================================
*/

class Solution2
{
public:

    string countAndSay(int n)
    {
        // Base case
        if (n == 1)
        {
            return "1";
        }

        // Generate previous term
        string say = countAndSay(n - 1);

        string result = "";

        // Traverse the string
        for (int i = 0; i < say.length(); i++)
        {
            int count = 1;

            // Count repeating characters
            while (i < say.length() - 1 && say[i] == say[i + 1])
            {
                count++;
                i++;
            }

            // Append count and character
            result += to_string(count);
            result += say[i];
        }

        return result;
    }
};



/*
=========================================================
Driver Code
=========================================================
*/

int main()
{
    int n = 5;

    Solution1 obj1;
    Solution2 obj2;

    cout << "Approach 1 Output: "
         << obj1.countAndSay(n) << endl;

    cout << "Approach 2 Output: "
         << obj2.countAndSay(n) << endl;

    return 0;
}